<?php
session_start();
include("includes.php");
if(isset($_POST['sub']))
{
    $uname=$_POST['uname'];
    $pass=$_POST['pass'];
    $query="select * from admin where uname='$uname' and pass='$pass'";
    $subresult=mysqli_query($conn,$query);
    $result=mysqli_fetch_array($subresult);
    $rows=mysqli_num_rows($subresult);
    {   
        if($rows>0)
        {
        $_SESSION['id']=$result['id'];
        $_SESSION['uname']=$result['uname'];
        $_SESSION['email']=$result['email'];
        $_SESSION['phno']=$result['phno'];
        $_SESSION['name']=$results['name'];
        header("location:controlpanel.php");
        }
        else
        {   
            header("location:login.php?error='wrong_uname_pass'");
        }
    }
}
else
{
header("location:login.php");
}
?>